name: Build and Push AI Anomaly Service

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/roshaan1103/ai-anomaly-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set lowercase image name (GHCR requires lowercase)
    - name: Set lowercase image name
      run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV

    # Enable Docker Buildx (for caching)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Cache Docker layers (CRITICAL for speed)
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # ogin to GHCR
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #Build image with cache
    - name: Build Docker image
      run: |
        docker buildx build \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache-new \
          -t $IMAGE_NAME_LC:${GITHUB_SHA} \
          -t $IMAGE_NAME_LC:latest \
          --load .

    # Move cache (required trick)
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    #Push image
    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME_LC:${GITHUB_SHA}
        docker push $IMAGE_NAME_LC:latest

    #Update Image tag
    - name: Update AI anomaly image tag
      run: |
       cd gitops
       sed -i "s|image: ghcr.io/roshaan1103/ai-anomaly-service:.*|image: ghcr.io/roshaan1103/ai-anomaly-service:${GITHUB_SHA}|g" environments/dev/aiops-app/ai-anomaly-deployment.yaml
